name: Publish RubyGem Workflow

on: 
  workflow_dispatch:

jobs:
  publish_rubygem:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Build Gem
        run: gem build gemspec/package-publish-test.gemspec

      - name: Publish to GitHub Package Registry
        run: gem push package-publish-test-*.gem --host https://rubygems.pkg.github.com/${{ michaelfdickey/package-publish-test }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
